### Get all characters
GET https://cse341-project2-5y6c.onrender.com/characters

### Get a single character
GET https://cse341-project2-5y6c.onrender.com/characters/6a0fafafcdf6808ce1648b41

### Create a new character
POST https://cse341-project2-5y6c.onrender.com/characters
Content-Type: application/json

{
    "name": "Toph",
    "nation": "Earth Kingdom",
    "bendingType": "Earthbending",
    "role": "Supporting character",
    "age": 12,
    "firstAppearance": "The Blind Bandit",
    "description": "Toph is a skilled Earthbender from the Earth Kingdom."
}

### Update an existing character
PUT https://cse341-project2-5y6c.onrender.com/characters/6a10d01c9d14328aefc1c96c
Content-Type: application/json

{
    "name": "",
    "nation": "Fire Nation",
    "bendingType": "Firebending",
    "role": "Protagonist",
    "age": "Twelve",
    "firstAppearance": "The Boy in the Iceberg",
    "description": "Zuk"
}

### Delete a character
DELETE https://cse341-project2-5y6c.onrender.com/characters/6a0fc1b1cc776b669c4212f7

### Get all episodes
GET https://cse341-project2-5y6c.onrender.com/episodes

### Get a single episode
GET https://cse341-project2-5y6c.onrender.com/episodes/6a0fd4493ebf2e2890f6bcef

### Create a new episode
POST https://cse341-project2-5y6c.onrender.com/episodes
Content-Type: application/json

{
    "title": "The Desert",
    "book": "Earth",
    "episode": 11,
    "description": "Aang and his friends get stranded in the desert and must find a way to survive. They encounter new challenges and make new allies along the way."
}

### Update an existing episode
PUT https://cse341-project2-5y6c.onrender.com/episodes/6a10d30f968f560b7d6128a8
Content-Type: application/json

{
    "title": "The Desert",
    "book": "Earth",
    "episode": 11,
    "description": "Aang and his friends get stranded in the desert and must find a way to survive. They encounter new challenges and make new allies along the way."
}

### Delete an episode
DELETE https://cse341-project2-5y6c.onrender.com/episodes/6a0fd7d31fbc7b987c2d0acc