### Get all userscharacters
GET https://cse341-project2-5y6c.onrender.com/characters

### Get a single character
GET https://cse341-project2-5y6c.onrender.com/characters/6a0fafafcdf6808ce1648b41

### Create a new character
POST https://cse341-project2-5y6c.onrender.com/characters
Content-Type: application/json

{
    "name": "Toph",
    "nation": "Earth Kingdom",
    "bendingType": "Earthbending",
    "role": "Supporting character",
    "age": 12,
    "firstAppearance": "The Blind Bandit",
    "description": "Toph is a skilled Earthbender from the Earth Kingdom."
}

### Update an existing character
PUT https://cse341-project2-5y6c.onrender.com/characters/6a0fafafcdf6808ce1648b41
Content-Type: application/json

{
    "name": "Zuko",
    "nation": "Fire Nation",
    "bendingType": "Firebending",
    "role": "Protagonist",
    "age": 16,
    "firstAppearance": "The Boy in the Iceberg",
    "description": "Zuko is a skilled Firebender from the Fire Nation. He is the crown prince of the Fire Nation."
}

### Delete a character
DELETE https://cse341-project2-5y6c.onrender.com/characters/6a0fc1b1cc776b669c4212f7

